import type { SupportedSetDefinition } from '@/lib/types'

const LOC_BENJAMIN_EDWARDS_COLLECTION = 'Library of Congress Benjamin K. Edwards Collection'
const LOC_BASEBALL_CARDS_SOURCE_URL = 'https://www.loc.gov/pictures/collection/bbc/sets.html'
const LOC_RIGHTS_STATUS = 'No known restrictions on publication'
const LOC_RIGHTS_NOTE = 'Library of Congress Rights Advisory: No known restrictions on publication.'

type PrewarExpansionConfig = {
  slug: string
  displayName: string
  name: string
  classificationCode: string
  yearStart: number
  yearEnd: number
  issuer: string
  category: string
  totalCards: number
  shortDescription: string
  longDescription: string
  sortOrder: number
  featured?: boolean
}

function makePrewarExpansionSet(config: PrewarExpansionConfig): SupportedSetDefinition {
  const yearRange = config.yearStart === config.yearEnd ? `${config.yearStart}` : `${config.yearStart}-${config.yearEnd}`

  return {
    setSlug: config.slug,
    setLabel: config.displayName,
    name: config.name,
    displayName: config.displayName,
    classificationCode: config.classificationCode,
    yearRange,
    year: config.yearStart,
    yearStart: config.yearStart,
    yearEnd: config.yearEnd,
    brand: config.classificationCode,
    setName: config.name,
    issuer: config.issuer,
    era: 'Pre-War',
    category: config.category,
    shortDescription: config.shortDescription,
    description: config.shortDescription,
    longDescription: config.longDescription,
    historicalOverview: config.longDescription,
    whyItMatters: config.shortDescription,
    collectionGroup: 'Pre-War Universe',
    totalCards: config.totalCards,
    sourceCollection: LOC_BENJAMIN_EDWARDS_COLLECTION,
    sourceName: LOC_BENJAMIN_EDWARDS_COLLECTION,
    sourceUrl: LOC_BASEBALL_CARDS_SOURCE_URL,
    rightsStatus: LOC_RIGHTS_STATUS,
    rightsNote: LOC_RIGHTS_NOTE,
    isPublicDomainImageSet: true,
    sortOrder: config.sortOrder,
    featured: config.featured ?? false,
    // LOC lot coverage is image/source coverage, not proof of a complete hobby checklist.
    checklistStatus: 'in_progress',
    featuredCardIds: [],
  }
}

export const PREWAR_EXPANSION_SETS: SupportedSetDefinition[] = [
  makePrewarExpansionSet({
    slug: 'n172-old-judge',
    displayName: 'N172 Old Judge',
    name: 'Old Judge',
    classificationCode: 'N172',
    yearStart: 1887,
    yearEnd: 1890,
    issuer: 'Goodwin & Co.',
    category: '19th-century tobacco cards',
    totalCards: 476,
    shortDescription: 'The great 19th-century photo issue: studio poses, barehanded catchers, and early professional baseball in sepia.',
    longDescription: 'N172 Old Judge is one of the foundational baseball card issues, built around photographic studio portraits and team/player variations from the late 1880s.',
    sortOrder: 101,
    featured: true,
  }),
  makePrewarExpansionSet({
    slug: 't202-hassan-triple-folders',
    displayName: 'T202 Hassan Triple Folders',
    name: 'Hassan Triple Folders',
    classificationCode: 'T202',
    yearStart: 1912,
    yearEnd: 1912,
    issuer: 'Hassan Cigarettes',
    category: 'Folded tobacco cards',
    totalCards: 123,
    shortDescription: 'A dramatic fold-out format pairing player portraits with a center action scene.',
    longDescription: 'T202 Hassan Triple Folders turn the card into a small panoramic object, with two player panels flanking a baseball scene.',
    sortOrder: 102,
    featured: true,
  }),
  makePrewarExpansionSet({
    slug: 't201-mecca-double-folders',
    displayName: 'T201 Mecca Double Folders',
    name: 'Mecca Double Folders',
    classificationCode: 'T201',
    yearStart: 1911,
    yearEnd: 1911,
    issuer: 'Mecca Cigarettes',
    category: 'Folded tobacco cards',
    totalCards: 50,
    shortDescription: 'Double-player foldovers from the tobacco era, half card and half optical trick.',
    longDescription: 'T201 Mecca Double Folders use a hinged portrait concept where one card can reveal multiple player images depending on how it is folded.',
    sortOrder: 103,
    featured: true,
  }),
  makePrewarExpansionSet({
    slug: 't3-turkey-red-cabinets',
    displayName: 'T3 Turkey Red Cabinets',
    name: 'Turkey Red Cabinets',
    classificationCode: 'T3',
    yearStart: 1911,
    yearEnd: 1911,
    issuer: 'Turkey Red Cigarettes',
    category: 'Cabinet cards',
    totalCards: 95,
    shortDescription: 'Oversized cabinet cards that feel closer to wall art than pocket cards.',
    longDescription: 'T3 Turkey Red Cabinets are large-format pre-war display pieces, prized for their scale, lithography, and deadball star power.',
    sortOrder: 104,
    featured: true,
  }),
  makePrewarExpansionSet({
    slug: 't207-brown-backgrounds',
    displayName: 'T207 Brown Backgrounds',
    name: 'Brown Backgrounds',
    classificationCode: 'T207',
    yearStart: 1912,
    yearEnd: 1912,
    issuer: 'Recruit Little Cigars',
    category: 'Tobacco cards',
    totalCards: 200,
    shortDescription: 'Moody brown portraits with a tougher, quieter feel than T205 or T206.',
    longDescription: 'T207 Brown Backgrounds are known for subdued portrait work, scarce back combinations, and a checklist that rewards patient tobacco-card collectors.',
    sortOrder: 105,
    featured: true,
  }),
  makePrewarExpansionSet({
    slug: 't204-ramly-cigarettes',
    displayName: 'T204 Ramly Cigarettes',
    name: 'Ramly Cigarettes',
    classificationCode: 'T204',
    yearStart: 1909,
    yearEnd: 1909,
    issuer: 'Ramly Cigarettes',
    category: 'Ornate tobacco cards',
    totalCards: 55,
    shortDescription: 'Silver-framed portraits with one of the most distinctive border treatments in the hobby.',
    longDescription: 'T204 Ramly pairs photographic player portraits with ornate silver borders, making it one of the most immediately recognizable tobacco-card issues.',
    sortOrder: 106,
    featured: true,
  }),
  makePrewarExpansionSet({
    slug: 't212-obak',
    displayName: 'T212 Obak',
    name: 'Obak',
    classificationCode: 'T212',
    yearStart: 1909,
    yearEnd: 1911,
    issuer: 'Obak Cigarettes',
    category: 'Pacific Coast League tobacco cards',
    totalCards: 171,
    shortDescription: 'West Coast and minor league tobacco cards from the Obak universe.',
    longDescription: 'T212 Obak opens a Pacific Coast League rabbit hole, with regional players, minor league identities, and a different flavor of deadball-era collecting.',
    sortOrder: 107,
    featured: true,
  }),
  makePrewarExpansionSet({
    slug: 't200-fatima-team-cards',
    displayName: 'T200 Fatima Team Cards',
    name: 'Fatima Team Cards',
    classificationCode: 'T200',
    yearStart: 1913,
    yearEnd: 1913,
    issuer: 'Fatima Cigarettes',
    category: 'Team cards',
    totalCards: 13,
    shortDescription: 'Wide team photographs that turn a checklist into a clubhouse snapshot.',
    longDescription: 'T200 Fatima Team Cards collect full team images rather than single-player portraits, making them natural anchors for team and city collecting.',
    sortOrder: 108,
    featured: true,
  }),
  makePrewarExpansionSet({
    slug: 'n28-allen-ginter-worlds-champions',
    displayName: "N28 Allen & Ginter World's Champions",
    name: "Allen & Ginter World's Champions",
    classificationCode: 'N28',
    yearStart: 1887,
    yearEnd: 1887,
    issuer: 'Allen & Ginter',
    category: '19th-century champions cards',
    totalCards: 9,
    shortDescription: 'Early multi-sport champions with ornate lithography and baseball subjects tucked inside a broader world of sport.',
    longDescription: "N28 Allen & Ginter World's Champions belongs to the 19th-century tobacco-card tradition, mixing baseball with other celebrated athletes of the era.",
    sortOrder: 201,
  }),
  makePrewarExpansionSet({
    slug: 'n29-allen-ginter-worlds-champions',
    displayName: "N29 Allen & Ginter World's Champions",
    name: "Allen & Ginter World's Champions",
    classificationCode: 'N29',
    yearStart: 1888,
    yearEnd: 1888,
    issuer: 'Allen & Ginter',
    category: '19th-century champions cards',
    totalCards: 4,
    shortDescription: 'The follow-up champions issue, part sport card and part Victorian display piece.',
    longDescription: 'N29 continues the Allen & Ginter champions format, giving type collectors another ornate 19th-century lane.',
    sortOrder: 202,
  }),
  makePrewarExpansionSet({
    slug: 'n43-allen-ginter-worlds-champions',
    displayName: "N43 Allen & Ginter World's Champions",
    name: "Allen & Ginter World's Champions",
    classificationCode: 'N43',
    yearStart: 1888,
    yearEnd: 1888,
    issuer: 'Allen & Ginter',
    category: 'Oversized champions cards',
    totalCards: 5,
    shortDescription: 'Larger Allen & Ginter cabinet-style champions cards with strong type-card appeal.',
    longDescription: 'N43 expands the Allen & Ginter champions idea into a larger format, closer to a small display print than a standard card.',
    sortOrder: 203,
  }),
  makePrewarExpansionSet({
    slug: 'n284-buchner-gold-coin',
    displayName: 'N284 Buchner Gold Coin',
    name: 'Buchner Gold Coin',
    classificationCode: 'N284',
    yearStart: 1887,
    yearEnd: 1887,
    issuer: 'Buchner Tobacco',
    category: '19th-century tobacco cards',
    totalCards: 58,
    shortDescription: 'A 19th-century tobacco issue with crisp portraits and strong early type-card energy.',
    longDescription: 'N284 Buchner Gold Coin sits in the same broad 1880s collecting world as Old Judge and Allen & Ginter, with its own compact visual identity.',
    sortOrder: 204,
  }),
  makePrewarExpansionSet({
    slug: 'n175-gypsy-queens',
    displayName: 'N175 Gypsy Queens',
    name: 'Gypsy Queens',
    classificationCode: 'N175',
    yearStart: 1887,
    yearEnd: 1887,
    issuer: 'Goodwin & Co.',
    category: '19th-century tobacco cards',
    totalCards: 4,
    shortDescription: 'Scarce 1880s Goodwin cards for collectors who like early, difficult, and a little mysterious.',
    longDescription: 'N175 Gypsy Queens is a deep 19th-century issue connected to Goodwin’s tobacco-card world and prized by advanced pre-war collectors.',
    sortOrder: 205,
  }),
  makePrewarExpansionSet({
    slug: 'n690-kalamazoo-bats',
    displayName: 'N690 Kalamazoo Bats',
    name: 'Kalamazoo Bats',
    classificationCode: 'N690',
    yearStart: 1887,
    yearEnd: 1887,
    issuer: 'Charles Gross & Co.',
    category: '19th-century tobacco cards',
    totalCards: 1,
    shortDescription: 'One of the great 1880s baseball rabbit holes: scarce, early, and wonderfully specific.',
    longDescription: 'N690 Kalamazoo Bats gives collectors another 19th-century tobacco trail, especially appealing for type-card and early baseball specialists.',
    sortOrder: 206,
  }),
  makePrewarExpansionSet({
    slug: 'n162-goodwin-champions',
    displayName: 'N162 Goodwin Champions',
    name: 'Goodwin Champions',
    classificationCode: 'N162',
    yearStart: 1888,
    yearEnd: 1888,
    issuer: 'Goodwin & Co.',
    category: '19th-century champions cards',
    totalCards: 8,
    shortDescription: 'Goodwin’s champion-athlete issue, with baseball sitting inside a wider sporting culture.',
    longDescription: 'N162 Goodwin Champions is a multi-sport 1888 issue that helps show where baseball cards fit in the broader tobacco-card boom.',
    sortOrder: 207,
  }),
  makePrewarExpansionSet({
    slug: 'n173-old-judge-cabinets',
    displayName: 'N173 Old Judge Cabinets',
    name: 'Old Judge Cabinets',
    classificationCode: 'N173',
    yearStart: 1888,
    yearEnd: 1889,
    issuer: 'Goodwin & Co.',
    category: 'Cabinet cards',
    totalCards: 26,
    shortDescription: 'Oversized Old Judge photographs for collectors who want the 19th century in display-case form.',
    longDescription: 'N173 Old Judge Cabinets take the Old Judge studio-photo idea into a larger cabinet format, making them natural trophy pieces.',
    sortOrder: 208,
  }),
  makePrewarExpansionSet({
    slug: 'n300-mayos-cut-plug',
    displayName: "N300 Mayo's Cut Plug",
    name: "Mayo's Cut Plug",
    classificationCode: 'N300',
    yearStart: 1895,
    yearEnd: 1895,
    issuer: "Mayo's Cut Plug",
    category: '19th-century tobacco cards',
    totalCards: 3,
    shortDescription: 'Black-background 1890s baseball cards with a stark, unmistakable look.',
    longDescription: "N300 Mayo's Cut Plug brings the 19th-century shelf forward to 1895 with a darker, simpler visual language.",
    sortOrder: 209,
  }),
  makePrewarExpansionSet({
    slug: 'px7-domino-discs',
    displayName: 'PX7 Domino Discs',
    name: 'Domino Discs',
    classificationCode: 'PX7',
    yearStart: 1909,
    yearEnd: 1912,
    issuer: 'Domino',
    category: 'Discs',
    totalCards: 2,
    shortDescription: 'Round baseball collectibles from the era when the card format was still up for grabs.',
    longDescription: 'PX7 Domino Discs belong in the strange-format lane: not quite cards, not quite game pieces, but very much part of the early baseball collecting world.',
    sortOrder: 301,
  }),
  makePrewarExpansionSet({
    slug: 't209-contentnea-first-series',
    displayName: 'T209 Contentnea First Series',
    name: 'Contentnea First Series',
    classificationCode: 'T209',
    yearStart: 1910,
    yearEnd: 1910,
    issuer: 'Contentnea Cigarettes',
    category: 'Southern tobacco cards',
    totalCards: 10,
    shortDescription: 'Regional tobacco cards with Southern and minor league appeal.',
    longDescription: 'T209 Contentnea First Series belongs to the regional tobacco-card world, where local leagues and lesser-known players become the point.',
    sortOrder: 302,
  }),
  makePrewarExpansionSet({
    slug: 't209-contentnea-photo-series',
    displayName: 'T209 Contentnea Photo Series',
    name: 'Contentnea Photo Series',
    classificationCode: 'T209',
    yearStart: 1910,
    yearEnd: 1910,
    issuer: 'Contentnea Cigarettes',
    category: 'Southern tobacco cards',
    totalCards: 1,
    shortDescription: 'Photo-style Contentnea cards for collectors chasing regional Southern issues.',
    longDescription: 'T209 Contentnea Photo Series gives the Southern tobacco lane a different look, built around photographic player presentation.',
    sortOrder: 303,
  }),
  makePrewarExpansionSet({
    slug: 'e104-nadja-philadelphia-athletics',
    displayName: 'E104 Nadja Philadelphia Athletics',
    name: 'Nadja Philadelphia Athletics',
    classificationCode: 'E104',
    yearStart: 1910,
    yearEnd: 1910,
    issuer: 'Nadja Caramels',
    category: 'Regional candy cards',
    totalCards: 18,
    shortDescription: 'A focused Philadelphia Athletics candy-card issue with compact team-run appeal.',
    longDescription: 'E104 Nadja Philadelphia Athletics is a small regional candy-card target for collectors who like focused team chases.',
    sortOrder: 304,
  }),
  makePrewarExpansionSet({
    slug: 't210-old-mill-cigarettes',
    displayName: 'T210 Old Mill Cigarettes',
    name: 'Old Mill Cigarettes',
    classificationCode: 'T210',
    yearStart: 1910,
    yearEnd: 1910,
    issuer: 'Old Mill Cigarettes',
    category: 'Minor league tobacco cards',
    totalCards: 8,
    shortDescription: 'A sprawling minor league tobacco chase and one of the hobby’s great deep cuts.',
    longDescription: 'T210 Old Mill is built for rabbit-hole collectors: Southern leagues, minor league subjects, and a huge amount of regional texture.',
    sortOrder: 305,
  }),
  makePrewarExpansionSet({
    slug: 't332-helmar-stamps',
    displayName: 'T332 Helmar Stamps',
    name: 'Helmar Stamps',
    classificationCode: 'T332',
    yearStart: 1911,
    yearEnd: 1911,
    issuer: 'Helmar Cigarettes',
    category: 'Stamps',
    totalCards: 12,
    shortDescription: 'Tiny tobacco-era stamps with big type-collector personality.',
    longDescription: 'T332 Helmar Stamps are a compact, strange-format issue that works beautifully inside a broader pre-war type collection.',
    sortOrder: 306,
  }),
  makePrewarExpansionSet({
    slug: 't227-series-of-champions',
    displayName: 'T227 Series of Champions',
    name: 'Series of Champions',
    classificationCode: 'T227',
    yearStart: 1912,
    yearEnd: 1912,
    issuer: 'Miners Extra / Honest Long Cut',
    category: 'Champions cards',
    totalCards: 4,
    shortDescription: 'Small champions cards with a short baseball subset and strong type-card appeal.',
    longDescription: 'T227 Series of Champions sits between sport-card, tobacco-card, and type-card collecting, with baseball represented inside a wider champions issue.',
    sortOrder: 307,
  }),
  makePrewarExpansionSet({
    slug: 't222-fatima',
    displayName: 'T222 Fatima',
    name: 'Fatima',
    classificationCode: 'T222',
    yearStart: 1914,
    yearEnd: 1914,
    issuer: 'Fatima Cigarettes',
    category: 'Tobacco cards',
    totalCards: 7,
    shortDescription: 'A later tobacco-era issue with a quiet, photo-forward look.',
    longDescription: 'T222 Fatima extends the tobacco-card shelf into 1914, giving collectors another bridge between classic tobacco cards and later photo issues.',
    sortOrder: 308,
  }),
  makePrewarExpansionSet({
    slug: 't330-2-piedmont-art-stamps',
    displayName: 'T330-2 Piedmont Art Stamps',
    name: 'Piedmont Art Stamps',
    classificationCode: 'T330-2',
    yearStart: 1914,
    yearEnd: 1914,
    issuer: 'Piedmont Cigarettes',
    category: 'Stamps',
    totalCards: 2,
    shortDescription: 'Stamp-format baseball collectibles from the Piedmont orbit.',
    longDescription: 'T330-2 Piedmont Art Stamps are perfect for the strange-format shelf: small, graphic, and deeply tied to tobacco-era collecting.',
    sortOrder: 309,
  }),
  makePrewarExpansionSet({
    slug: 't4-obak-cabinets',
    displayName: 'T4 Obak Cabinets',
    name: 'Obak Cabinets',
    classificationCode: 'T4',
    yearStart: 1911,
    yearEnd: 1911,
    issuer: 'Obak Cigarettes',
    category: 'Cabinet cards',
    totalCards: 1,
    shortDescription: 'Oversized Pacific Coast League cabinets from the Obak world.',
    longDescription: 'T4 Obak Cabinets turn the Pacific Coast League lane into a display-card chase, with regional appeal and cabinet-card scale.',
    sortOrder: 310,
  }),
]

export const PREWAR_EXPANSION_SET_SLUGS = PREWAR_EXPANSION_SETS.map((set) => set.setSlug)
